### ISSUE TITLE
GS2 Compatibility / Missing Optimization

### ISSUE THREAD

**Issue by eirshy** [w-gates/dsp-vege-drop#1]
At (currently) [line 316](https://github.com/w-gates/dsp-vege-drop/blob/0b2375aef1a1bb00465d4e3a9e63bb131a010449/DysonSphereVegeDrop.cs#L316) you have a condition chain checking for whether the planet type is enabled, you method of doing so is string comparison to a hardcoded list of planet themes.

This results in two problems...
1) Galactic Scale 2 introduces new planet themes, which will cause this hard-coded list to be missing possible theme types; this cannot be fixed via adding more hardcoded themes, as GS2 can add new themes via user-side json.
2) O(n) string comparisons to match planet theme.

What I would suggest doing instead is maintaining a `HashSet<string>` that stores all disabled planet theme names, which allows you to simply add or remove themes when they're toggled, and makes the "are we allowed on this planet" check a single line O(1).
Then you can look into how to best autogenerate a setting for each theme (or just use an arbitrary ban list setting) for the GS2 support (if you feel like it).

**Comment by w-gates** [comment]
This mod is now deprecated. I wrote it to replace [DSP Drone Clearing](https://dsp.thunderstore.io/package/GreyHak/DSP_Drone_Clearing/); [LaserClearing](https://dsp.thunderstore.io/package/starfi5h/LaserClearing/) was then released by starfi5h which I prefer. I will probably not update this one.
